# Generated by Django 4.0 on 2021-12-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('saleboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='saleboard.item', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, to='gallery.Photo', verbose_name='Фотографии'),
        ),
    ]
