# Generated by Django 4.0 on 2021-12-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
