# Generated by Django 4.0 on 2021-12-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/%s-%s', verbose_name='Image')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saleboard.item')),
            ],
        ),
    ]
