# Generated by Django 4.0 on 2021-12-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleboard', '0003_alter_image_options_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saleboard.item')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
