# Generated by Django 4.0 on 2021-12-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboard', '0004_images_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/gallery/', verbose_name='Изображение'),
        ),
    ]
