# Generated by Django 4.0 on 2021-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboard', '0006_remove_images_imagen_images_images_alter_images_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='gallery/%d-%s/', verbose_name='Изображение'),
        ),
    ]
